version: "3.7"

services:
  backend:
    build:
      context: ./backend
    container_name: backend-starshipbattle
    ports:
      - 8000:8000
    volumes:
      - ./backend:/usr/src/app
    command: python -u manage.py runserver 0.0.0.0:8000
  redis:
    image: redis
    ports:
      - 6379:6379
