version: "3.7"

services:
  redis:
    image: redis
    ports:
      - 6379:6379
  db:
    image: postgres
    environment:
      - POSTGRES_USER=starship
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=starshipbattle
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./backend
    container_name: backend-starshipbattle
    ports:
      - 8000:8000
    volumes:
      - ./backend:/usr/src/app
    command: ./serve.sh
    depends_on:
      - db
      - redis
  frontend:
    build:
      context: ./frontend
    container_name: frontend-starshipbattle
    ports:
      - 8080:80
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/
