# Generated by Django 4.1.4 on 2023-06-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_status",
            field=models.CharField(
                choices=[("awaiting", "Awaiting"), ("started", "Started")],
                default="awaiting",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
